spring:
  profiles:
    #上线时切换环境
    active: dev
  datasource:
    url: jdbc:mysql://dev.mysql.ywsoftware.cn:3306/numysql_hgyl?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8
    username: numysql_hgyl
    password: numysql_hgyl
    #druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 1
    #最大连接等待超时时间
    maxWait: 60000
    #打开PSCache，并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
    #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
  mvc:
    view:
      prefix: /webapp/web-static/html
      suffix: .html
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: test
#    password: test
#    virtual-host: /
server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*.xml

#配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
filters: stat, wall, log4j







