spring:
  datasource:
    url: jdbc:mysql://dev.mysql.ywsoftware.cn:3306/numysql_hgyl
    username: numysql_hgyl
    password: numysql_hgyl
server:
  port: 8081


mybatis:
  mapper-locations: classpath:mapper/*.xml



