spring:
  datasource:
    url: jdbc:mysql://localhost/numysql_qxy?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2b8&allowMultiQueries=true
    username: root
    password: 914914
server:
  port: 8081



